# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dbddb92fbcd9b701787901a342e05faf0401eb11ae4ae7d6efbdf946a7276f9498b1169470a1a6d00fed0cbbc0fa3e5b227e9d60706ffad4c61e1602a888b33

test:
  secret_key_base: 94355016fb078d8c979a9e95e627b63195af74053c5d8d96b26b9242879ecd4e4eb5b73d6a4579fb57075a840d647108e94862f41c3eaca0f2a790112a5d6a0f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
